version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@postgres:5432/myapp
      - JWT_SECRET=development-secret-key
      - JWT_EXPIRES_IN=7d
      - REFRESH_TOKEN_SECRET=refresh-secret-key
      - REFRESH_TOKEN_EXPIRES_IN=30d
    depends_on:
      - postgres
      - redis
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  # Mock push notification service for development
  push-notification-mock:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./backend/mock-services/push-notifications:/app
    command: node server.js
    ports:
      - "4000:4000"

volumes:
  postgres_data:
  redis_data: